### PR TITLE
Dockerize `ksv`

### PR DESCRIPTION
**Pull request by abitrolly**
I use `podman`, but the instructions should work with `docker` the same.

To build the image.
```
podman build . --tag ksv
```
To test it.
```
podman run ksv
```
To share current directory and run interactively.
```
podman run -v "$(pwd):/share":Z -w "/share" -it ksv
```
The full command I am using to inspect contents of `.snap` file using `.ksy` definition placed in current dir.
```
podman run -v "$(pwd):/share":Z -w "/share" -it ksv v3.snap squashfs_superblock.ksy
```
This generated the following output.

image

Should there be colors?

### CODE REVIEW

**Comment by abitrolly** [comment]
@GreyCat any comments? I can try to setup a GitHub Action to post the image to DockerHub.

**Comment by GreyCat** [comment]
Apologies for late reply!

Having Docker container makes perfect sense, let me merge this into the repo.

**Comment by abitrolly** [comment]
@GreyCat awesome. If you could you place a label `hacktoberfest-accepted` I may get a better chance to get a t-shirt in exchange for some personal data. :D

**Comment by abitrolly** [comment]
More info is here https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by GreyCat** [comment]
Good luck :)

**Comment by abitrolly** [comment]
@GreyCat thanks. I am not sure it will qualify as the PR was made before October. That's why there is #41 that improves image usage process. )

**Pull request merged**
