### PR TITLE
GitHub workflow to push Docker image

### PR DESCRIPTION
**Pull request by abitrolly**
I haven't tested it, because it only triggers from `master` and requires valid credentials set for `kaitai/ksv` repo, but it should work.

### CODE REVIEW

**Review by generalmimon — APPROVED** [review]
Thanks for this contribution! I'm currently working with @GreyCat on creating a bot account for the automated publishing, so once it's done, I'll fill in the secrets and we can merge this right away.

**Comment by generalmimon** [comment]
Our [`kaitaibot`](https://hub.docker.com/u/kaitaibot) is up and running, so let's see if he can handle the first publication.

**Comment by generalmimon** [comment]
> Our [**kaitaibot**](https://hub.docker.com/u/kaitaibot) is up and running, so let's see if he can handle the first publication.

He did it! 🤖 🎉

Check out https://hub.docker.com/r/kaitai/ksv

**Comment by abitrolly** [comment]
Only 6 pulls so far. )

image 

Let;s see how it goes in a week. Might worth mentioning that `ksc` is also bundled.

**Comment by abitrolly** [comment]
The docker image description can be different for the Docker image - ohttps://hub.docker.com/r/kaitai/ksv 

First, I would change the description.
```diff
-Kaitai Struct: console visualizer and hex viewer 
+Kaitai Struct compiler, console visualizer and hex viewer 
```

Then replace all unrelated info like "Downloading and installing" with image usage guidelines. How to run visualizer and how to run compiler from the image.

**Comment by generalmimon** [comment]
> The docker image description can be different for the Docker image

Yeah, that's what @GreyCat suggested in our private conversation as well. I pushed the current version to branch [`docker-readme`](https://github.com/kaitai-io/kaitai_struct_visualizer/tree/docker-readme). If you have plans to change it, feel free to open a PR targeting that branch.

**Comment by abitrolly** [comment]
@generalmimon I actually thought about `README.DockerHub.md` in the root.

**Comment by generalmimon** [comment]
@abitrolly:

> I actually thought about `README.DockerHub.md` in the root.

Yeah, that's more simple and transparent, let's go with that. Not sure what I was thinking...

**Comment by generalmimon** [comment]
@abitrolly I just changed `README.DockerHub.md` to `README-dockerhub.md` - let's not be too creative in file names.

**Comment by abitrolly** [comment]
@generalmimon that makes secondary README stand up before the main one.

image

**Comment by generalmimon** [comment]
> that makes secondary README stand up before the main one.

Totally irrelevant. There isn't any reason here to optimize file names for the alphabetical order in the directory. And if there was some functional reason, the only acceptable solution is to use a numerical prefix (like `01_first.txt`, `02_second.txt`), not some weird double-file-extension hack that _works_ only because

<pre><code>README.|<b>D</b>|ockerHub.md
README.|<b>m</b>|d
</code></pre>

... **D** comes earlier in the alphabet than **m**.

And neither `.DockerHub` nor `.DockerHub.md` belong to any reputable file extensions. We just mean `DockerHub` to be a regular part of the file name, just as `README` is.

Also, the `DockerHub` identifier incomprehensibly uses CamelCase, which violates file naming conventions used by the rest of Kaitai Struct repos (well, to be fair, `snake_case` is mostly used, but I often forget about it and thoughtlessly put `kebab-case` there only to correct it later - let's do it: https://github.com/kaitai-io/kaitai_struct_visualizer/commit/761c2c39fd1c1415cd48a30d0d8e3466610e7371).

**Comment by abitrolly** [comment]
Certainly a good moment for a long Friday bikeshedding thread. :D I don't really feel like starting the morning with it, so I will just pass the privilege to @KOLANICH to throw in his opinion here. )

**Pull request merged**
