### PR TITLE
Unify and change color palette for both ANSI and Windows console

### PR DESCRIPTION
**Pull request by generalmimon**
### **ANSI** console

before-ansi

### **Windows** console

before-windows

### **ANSI** console

after-ansi

### **Windows** console

after-windows

### CODE REVIEW

**Comment by generalmimon** [comment]
FWIW, the test .ksy for the demonstration above looked like this:

<details>
  <summary>levels.ksy</summary>

```ksy
meta:
  id: levels
seq:
  - id: one_a
    size: 1
  - id: nested
    type: level_one
  - id: one_b
    size: 1
types:
  level_one:
    seq:
      - id: two_a
        size: 2
      - id: nested
        type: level_two
      - id: two_b
        size: 2
  level_two:
    seq:
      - id: three_a
        size: 3
      - id: nested
        type: level_three
      - id: three_b
        size: 3
  level_three:
    seq:
      - id: four_a
        size: 4
      - id: nested
        type: level_four
      - id: four_b
        size: 4
  level_four:
    seq:
      - id: five_a
        size: 5
      - id: five_b
        size: 5
```

</details>

**Review by ams-tschoening — APPROVED** [review]
I wasn't able to trigger the blue color with my files, but that might not mean much. I'm using some old Ruby, KS-runtime, cmd.exe and stuff, maybe there's some difference or I'm not understanding something in this PR. The important thing is that seems still work, so no need for further debugging for me right now. Don't have the time anyway.

**Comment by generalmimon** [comment]
@ams-tschoening Thanks for your comment! Everyone is busy nowadays, so I'm glad that you managed to find some time for this little thing.

> The important thing is that seems still work, so no need for further debugging for me right now.

Yeah, it's basically guaranteed to work the same, because I haven't changed anything but the colors.

> I wasn't able to trigger the blue color with my files, but that might not mean much.

I didn't expect you to try it locally :) I recorded how it looks like before/after [in the initial PR comment](https://github.com/kaitai-io/kaitai_struct_visualizer/pull/54#issue-1580843892), so pretty much just whether you like it or not.

But if you want to try for yourself how it works, I shared a test `.ksy` spec in this comment above: https://github.com/kaitai-io/kaitai_struct_visualizer/pull/54#issuecomment-1426771381

At first, I also didn't really know what these colors are for :-) But apparently they are used to indicate regions occupied by fields on different levels. The byte range of the field currently selected in the object tree is highlighted white (`#ffffff`), the parent type of this field is highlighted "bright aqua" `#61d6d6` and so on. The important part is that these usertypes doesn't have their own substreams (they all reuse the same stream), because otherwise they would not be visible in the same hex dump in the console visualizer. This is where `ksv` differs from the Web IDE, for example.

> maybe there's some difference or I'm not understanding something in this PR

The colors have been changed, that's what this PR is about :D

**Comment by generalmimon** [comment]
Can anyone check if the new colors shown in https://github.com/kaitai-io/kaitai_struct_visualizer/pull/54#issue-1580843892 are OK? Cc @GreyCat, @dgelessus

Or you can suggest other colors, but I think they should be picked from this list so we can have a consistent color palette between ANSI and Windows consoles:

https://github.com/kaitai-io/kaitai_struct_visualizer/blob/b16ae0de787a0424c13447534eb07c0e6886254c/lib/kaitai/console_ansi.rb#L45-L60

You can also check out the branch and try it locally on the `.ksy` I posted above if you want: https://github.com/kaitai-io/kaitai_struct_visualizer/pull/54#issuecomment-1426771381

**Pull request merged**
